CREATE USER 'saad'@'localhost' IDENTIFIED BY 'hello1234';



GRANT SELECT,UPDATE ON p200051_saad.EMPLOYEE TO 'saad'@'localhost';




GRANT SELECT ON p200051_saad.EMP_DETAILS TO 'saad'@'localhost';



GRANT ALL PRIVILEGES ON fb. * TO 'saad'@'localhost';




GRANT CREATE ON *.* TO 'saad'@'localhost';



REVOKE SELECT ON p200051_saad.EMP_DETAILS FROM 'saad'@'localhost';



INSERT INTO THEMEPARK VALUES('T1000' , 'DUMMY1' , 'PWR' , 'PK');
INSERT INTO THEMEPARK VALUES('T1001' , 'DUMMY2' , 'PWR' , 'PK');
SAVEPOINT S1;
INSERT INTO THEMEPARK VALUES('T1002' , 'DUMMY3' , 'PWR' , 'PK');
INSERT INTO THEMEPARK VALUES('T1003' , 'DUMMY4' , 'PWR' , 'PK');
SAVEPOINT S2;
INSERT INTO THEMEPARK VALUES('T1004' , 'DUMMY5' , 'PWR' , 'PK');
INSERT INTO THEMEPARK VALUES('T1005' , 'DUMMY6' , 'PWR' , 'PK');











